import re

GREEN = "\033[32m"
YELLOW = "\033[33m"
RED = "\033[31m"
CYAN = "\033[36m"
RESET = "\033[0m"

ANSI_ESCAPE = re.compile(r"\033\[[0-9;]*m")

BONUS_HARVEST_CHANCE = 0.1
UPGRADE_UNLOCK_GOLD = 10

SAAT_BOY_INTERVAL = 12
HARVEST_HELPER_INTERVAL = 15

MILL_PRICE = 750
MILL_DURATION = 180
FLOUR_SELL_PRICE = 5

MIN_UPGRADE_INTERVAL = 1
MAX_UPGRADE_ACTIONS = 5

GARDEN_SIZE = 5
MAX_GARDENS = 9
GARDENS_PER_ROW = 3
GARDEN_PANEL_WIDTH = 17

PROCESSOR_PANEL_WIDTH = (
    GARDENS_PER_ROW * GARDEN_PANEL_WIDTH
    + (GARDENS_PER_ROW - 1) * 2
)

PROCESSOR_BAR_WIDTH = 10

LAYOUT_COLUMN_GAP = 4

SHOP_PANEL_WIDTH = 50
SHOP_PAGE_SIZE = 5

SELL_AMOUNTS = [1, 5, 10, "all"]

SAVE_FILE = "savegame.json"